[workspace]
resolver = "2"
members = ["lua-script-engine"]

[workspace.package]
edition = "2021"
license = "Proprietary"

[workspace.dependencies]
abi_stable = "0.11"
newengine-plugin-api = { package = "newengine-plugin-kit", path = "../../NewEngine/neocore2/crates/newengine-plugin-kit" }
newengine-scripting-api = { path = "../../NewEngine/neocore2/crates/newengine-scripting-api" }
newengine-service-api = { path = "../../NewEngine/neocore2/crates/newengine-service-api" }
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mlua = { version = "0.12.0", features = ["lua54", "vendored", "send"] }

[profile.release]
debug = 0
strip = "symbols"
